# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:52:31+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    ApmclCertificatePostRequest,
    ApmclCertificatePostResponse,
    ApmclCertificatePostResponse1,
    ApmclCertificatePostResponse2,
    ApmclCertificatePostResponse3,
    ApmclCertificatePostResponse4,
    ApmclCertificatePostResponse5,
    ApmclCertificatePostResponse6,
)

app = MCPProxy(
    description='APIs provided by Department of Agricultural Marketing, Karnataka.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Department of Agricultural Marketing, Karnataka',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/apmcservices/v3'}],
)


@app.post(
    '/apmcl/certificate',
    description=""" API to verify Agriculture Produce Market Committee License. """,
    tags=['agriculture_regulations'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def apmcl(body: ApmclCertificatePostRequest = None):
    """
    Agriculture Produce Market Committee License
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
